import test from "node:test";
import assert from "node:assert/strict";
import { buildRunnerArgv, compactResult, validateInput, WORKLOAD_CLASSES, inferMode, inferPhase, parseEvent } from "../agent/lib/arc-runtime.ts";
const base:any={outcome:"ship",scope:"bounded",verification:"tests",preserved_behavior:"all",prohibitions:"none",label:"Issue 1",cwd:"."};
test("automatic argv follows ARC Pi ordering",()=>{assert.equal(inferPhase("review"),"verify");assert.equal(inferMode("verify"),"review");const a=buildRunnerArgv({...base,phase:"explore",task_class:"  feature ",route_rationale:" selected ",task_slug:"issue-1"});const task=a[a.indexOf("--task")+1];assert.deepEqual(a,["run","--mode","analyze","--routing-policy","runner-routing-v4","--phase","explore","--task",task,"--cwd",process.cwd(),"--label","issue-1","--task-class","feature","--route-rationale","selected","--task-slug","issue-1"]);for(const flag of ["--backend","--worker-model","--fallback","--timeout"])assert(!a.includes(flag));});
test("Eco automatic routing omits only the routing marker",()=>{const a=buildRunnerArgv({...base,phase:"plan",orchestrator:"eco"});const task=a[a.indexOf("--task")+1];assert.deepEqual(a,["run","--mode","analyze","--phase","plan","--task",task,"--cwd",process.cwd(),"--label","issue-1"]);});
test("explicit route owns routing but carries mode and phase",()=>{const a=buildRunnerArgv({...base,phase:"research",route:"fable-explore"});const task=a[a.indexOf("--task")+1];assert.deepEqual(a,["run","--mode","analyze","--route","fable-explore","--phase","research","--task",task,"--cwd",process.cwd(),"--label","issue-1"]);assert(!a.includes("--routing-policy"));assert(!a.includes("--workload-class"));});
test("all canonical workload classes and authorization",()=>{for(const workload_class of WORKLOAD_CLASSES){const a=buildRunnerArgv({...base,phase:"implement",workload_class,implement_authorized:true});assert.deepEqual(a.slice(-2),["--workload-class",workload_class]);assert.throws(()=>validateInput({...base,phase:"implement",workload_class}),/authorization/);}});
test("validation rejects phase, route, workload, and authorization misuse",()=>{assert.throws(()=>validateInput({...base,phase:"verify",mode:"analyze"}),/conflicts/);assert.throws(()=>validateInput({...base,phase:"verify",route:"fable-explore"}),/route conflicts/);assert.throws(()=>validateInput({...base,phase:"explore",deploy_authorized:false}),/only valid for Deploy/);assert.throws(()=>validateInput({...base,phase:"verify",implement_authorized:false}),/only valid for Implement/);assert.throws(()=>validateInput({...base,phase:"explore",workload_class:"easy-light"}),/only valid for Implement/);assert.throws(()=>validateInput({...base,phase:"implement",route:"fable-implement",workload_class:"easy-light",implement_authorized:true}),/explicit routes/);assert.throws(()=>validateInput({...base,phase:"deploy",route:"fable-implement",deploy_authorized:true}),/does not accept/);assert.throws(()=>validateInput({...base,phase:"analyze"}),/parent-local/);assert.throws(()=>validateInput({...base,phase:"explore",background:true}),/background/);assert.throws(()=>validateInput({...base,phase:"explore",route:"fable-explore",orchestrator:"eco"}),/automatic-only/);});
test("task_slug is safe and Analyze-only",()=>{for(const phase of ["explore","research","plan"] as const)assert.doesNotThrow(()=>validateInput({...base,phase,task_slug:"issue-1"}));assert.doesNotThrow(()=>validateInput({...base,phase:"research",route:"fable-explore",task_slug:"issue-1"}));assert.throws(()=>validateInput({...base,route:"sol-check",task_slug:"issue-1"}),/Analyze/);assert.throws(()=>validateInput({...base,phase:"verify",task_slug:"issue-1"}),/Analyze/);assert.throws(()=>validateInput({...base,phase:"implement",workload_class:"easy-light",implement_authorized:true,task_slug:"issue-1"}),/Analyze/);assert.throws(()=>validateInput({...base,phase:"deploy",deploy_authorized:true,task_slug:"issue-1"}),/Analyze/);for(const task_slug of ["../issue","Issue-1","issue/1"])assert.throws(()=>validateInput({...base,phase:"explore",task_slug}),/invalid task_slug/);});
test("Deploy argv carries only the supported authorization flag",()=>{const a=buildRunnerArgv({...base,phase:"deploy",deploy_authorized:true});const task=a[a.indexOf("--task")+1];assert.deepEqual(a,["run","--mode","implement","--routing-policy","runner-routing-v4","--phase","deploy","--deploy-authorized","true","--task",task,"--cwd",process.cwd(),"--label","issue-1"]);});
test("strict final result is compact and redacted",()=>{const r:any=compactResult(JSON.stringify({status:"completed",summary:"token=secret-value",changes:Array(25).fill("a".repeat(600)),verification:[],risks:[],next_actions:[]}),"completed");assert.equal(r.status,"completed");assert.equal(r.changes.length,20);assert.equal(r.changes[0].length,500);assert(!JSON.stringify(r).includes("secret-value"));const token="github_pat_1234567890abcdefghij";const tokenOnly:any=compactResult(JSON.stringify({status:"completed",summary:token,changes:[],verification:[],risks:[],next_actions:[]}));assert(!JSON.stringify(tokenOnly).includes(token));assert.equal(compactResult('{"summary":"raw worker output"}',"failed").status,"blocked");assert(!JSON.stringify(compactResult('{"summary":"raw worker output"}',"failed")).includes("raw worker output"));});
test("strict final result rejects non-string evidence and preserves blocked evidence",()=>{const evidence={status:"completed",summary:"ok",changes:[],verification:[],risks:[],next_actions:[]};for(const key of ["changes","verification","risks","next_actions"]){const malformed:any={...evidence,[key]:["valid",{raw:"output"},42]};const result:any=compactResult(JSON.stringify(malformed));assert.equal(result.status,"blocked");assert.deepEqual(result.changes,[]);}const blocked:any=compactResult(JSON.stringify({...evidence,status:"blocked",summary:"cannot proceed",risks:["dependency unavailable"],next_actions:["retry"]}));assert.equal(blocked.status,"blocked");assert.equal(blocked.summary,"cannot proceed");assert.deepEqual(blocked.risks,["dependency unavailable"]);});
const event=(value:unknown)=>parseEvent(`arc-orchestrator: event: ${JSON.stringify(value)}`);
test("accepts ARC Pi v1 phase, activity, and files events",()=>{
 assert.deepEqual(event({v:1,kind:"phase",seq:1,at:0,data:{phase:"review",status:"validating",model:"gpt-5.6-sol"}}),{v:1,kind:"phase",seq:1,at:0,data:{phase:"review",status:"validating",model:"gpt-5.6-sol"}});
 assert(event({v:1,kind:"activity",seq:2,at:10,data:{status:"waiting-provider",tool:"functions.read",count:0}}));
 assert.deepEqual((event({v:1,kind:"files",seq:3,at:11,data:{count:2,files:[{file:"agent/lib/a.ts",status:"modified"},{file:".env",status:"unknown"}]}}) as any).data.files,[{file:"agent/lib/a.ts",status:"modified"}]);
});
test("rejects invalid event fields and unsafe content",()=>{
 assert.equal(event({v:1,kind:"phase",seq:1,at:0,data:{phase:"plan",status:"started"}}),undefined);
 assert.equal(event({v:1,kind:"phase",seq:1,at:0,extra:true,data:{phase:"plan",status:"running"}}),undefined);
 assert.equal(event({v:1,kind:"files",seq:1,at:0,data:{count:1,files:[{file:"/etc/passwd",status:"modified"}]}}),undefined);
 assert.equal(event({v:1,kind:"phase",seq:1,at:0,data:{phase:"plan",status:"running",model:"token=secret-value"}}),undefined);
});
test("requires positive safe seq and non-negative safe at",()=>{
 const data={phase:"explore",status:"preparing"};
 for(const seq of [0,-1,1.5,Number.MAX_SAFE_INTEGER+1])assert.equal(event({v:1,kind:"phase",seq,at:0,data}),undefined);
 for(const at of [-1,1.5,Number.MAX_SAFE_INTEGER+1])assert.equal(event({v:1,kind:"phase",seq:1,at,data}),undefined);
 assert(event({v:1,kind:"phase",seq:Number.MAX_SAFE_INTEGER,at:Number.MAX_SAFE_INTEGER,data}));
});
