import { access, mkdir, rename, stat, writeFile, readFile } from "node:fs/promises";
import { constants } from "node:fs";
import { delimiter, join, resolve, isAbsolute, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn as nodeSpawn } from "node:child_process";
import { randomUUID } from "node:crypto";

export const WORKLOAD_CLASSES = ["hard-heavy","hard-medium","hard-light","medium-heavy","medium-medium","medium-light","easy-heavy","easy-medium","easy-light"] as const;
export type WorkloadClass=typeof WORKLOAD_CLASSES[number];
export type Phase="explore"|"research"|"plan"|"implement"|"verify"|"deploy";
export type Mode="analyze"|"implement"|"review";
export type DelegateInput={outcome:string;scope:string;verification:string;preserved_behavior:string;prohibitions:string;label:string;mode?:Mode;phase?:Phase;route?:string;context?:string;cwd?:string;task_class?:string;route_rationale?:string;workload_class?:WorkloadClass;orchestrator?:"eco";implement_authorized?:boolean;deploy_authorized?:boolean;decision_refs?:string[];assumption_refs?:string[];readiness_acknowledged?:boolean;task_slug?:string;background?:boolean};
export const phases=new Set<Phase>(["explore","research","plan","implement","verify","deploy"]);
export const MAX_OUTPUT=24000;
const slug=/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
const bases=["fable","fable-5.1","sol","gpt-5.6-sol","luna","gpt-5.6-luna","gpt-5.5","opus","opus-5","opus-4.8","grok","grok-4.6","minimax","minimax-m3","composer","composer-2.5","cursor-auto","glm-5.3-flash","glm-5.3","deepseek-v4-pro","deepseek-v4-flash","go-kimi-k3","qwen-3.8-max","muse-spark-1.2","glm-5.2","kimi-k2.7-code","go-grok-4.6","go-luna"] as const;
export const PUBLIC_ROUTES=new Set(bases.flatMap(b=>[`${b}-explore`,`${b}-implement`,`${b}-check` ]));
const routeParts=(r:string)=>{for(const suffix of ["explore","implement","check"] as const){const m=`-${suffix}`;if(r.endsWith(m))return {suffix,base:r.slice(0,-m.length)};}return undefined;};
export function inferMode(phase?:Phase,mode?:Mode):Mode {if(phase){if(["explore","research","plan"].includes(phase))return "analyze";if(phase==="verify")return "review";return "implement";}return mode??"analyze";}
export function inferPhase(mode?:Mode,phase?:Phase):Phase {if(phase)return phase;return mode==="review"?"verify":mode==="implement"?"implement":"explore";}
export function validateInput(i:DelegateInput):{mode:Mode;phase:Phase}{
 for(const k of ["outcome","scope","verification","preserved_behavior","prohibitions","label"] as const)if(typeof i[k]!=="string"||!i[k].trim())throw Error(`missing required field: ${k}`);
 if(i.phase as string === "analyze")throw Error("analyze is parent-local"); const rp=i.route?routeParts(i.route):undefined;
 const routePhase=rp?(rp.suffix==="explore"?"explore":rp.suffix==="check"?"verify":"implement"):undefined;
 const phase=inferPhase(i.mode,i.phase??routePhase),mode=inferMode(phase,i.mode);
 if(i.mode&&i.mode!==mode)throw Error("mode conflicts with phase"); if(!phases.has(phase))throw Error("invalid phase");
 for(const key of ["deploy_authorized","implement_authorized","readiness_acknowledged","background"] as const)if(i[key]!==undefined&&typeof i[key]!=="boolean")throw Error(`${key} must be boolean`);
 if(i.orchestrator!==undefined&&i.orchestrator!=="eco")throw Error('orchestrator must be "eco"');
 if(i.deploy_authorized!==undefined&&phase!=="deploy")throw Error("deploy_authorized is only valid for Deploy");
 if(i.implement_authorized!==undefined&&phase!=="implement")throw Error("implement_authorized is only valid for Implement");
 if(i.route!==undefined){if(!PUBLIC_ROUTES.has(i.route)||!rp)throw Error("invalid public route");if(phase==="deploy")throw Error("Deploy does not accept an explicit public route");const expected=rp.suffix==="explore"?"analyze":rp.suffix==="check"?"review":"implement";if(mode!==expected)throw Error("route conflicts with phase or mode");if(i.workload_class!==undefined)throw Error("explicit routes do not accept workload_class");}
 if(i.task_slug!==undefined){if(typeof i.task_slug!=="string"||!slug.test(i.task_slug))throw Error("invalid task_slug");if(mode!=="analyze")throw Error("task_slug is only valid for Analyze phases");}
 for(const key of ["task_class","route_rationale"] as const)if(i[key]!==undefined&&(typeof i[key]!=="string"||!i[key]!.trim()))throw Error(`invalid ${key}`);
 for(const key of ["decision_refs","assumption_refs"] as const)if(i[key]!==undefined&&(!Array.isArray(i[key])||new Set(i[key]).size!==i[key].length||i[key].some(x=>typeof x!=="string"||!x.trim())))throw Error(`invalid ${key}`);
 if(i.workload_class!==undefined&&!WORKLOAD_CLASSES.includes(i.workload_class))throw Error("invalid workload_class");
 if(i.workload_class!==undefined&&phase!=="implement")throw Error("workload_class is only valid for Implement");
 if(!i.route&&phase==="implement"&&(!i.workload_class||i.implement_authorized!==true))throw Error("automatic Implement requires canonical workload_class and implement authorization metadata");
 if(phase==="deploy"&&i.deploy_authorized!==true)throw Error("Deploy requires authorization metadata");
 if(i.background===true)throw Error("background execution is not exposed by synchronous arc_delegate"); if(i.orchestrator!==undefined&&i.route)throw Error("Eco is automatic-only"); return {mode,phase};
}
const contractText=(v:string,max=3000)=>v.replace(/\r\n?/g,"\n").split("\n").map(line=>bounded(line,max)).join("\n").slice(0,max).trim();
export function safeDelegateLabel(input?:string):string{const cleaned=(input||"arc-delegate").toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^[^a-z0-9]+/,"").replace(/[^a-z0-9]+$/,"").slice(0,64);return cleaned||"arc-delegate";}
export function taskContract(i:DelegateInput){const {mode,phase}=validateInput(i),label=safeDelegateLabel(i.label);const route=i.route?`explicit route ${i.route}`:i.orchestrator==="eco"?`automatic Eco (${mode})`:`automatic runner-routing-v4 (${mode})`;const deployRule=phase==="deploy"?"Do not deploy beyond the exact authorized outcome and scope above.":"Do not deploy.";const sections=[`You are an ARC worker. Phase: ${phase}. Mode: ${mode}. Route: ${route}.`,"",`Safe label: ${label}`];if(i.context?.trim())sections.push("","Context:",contractText(i.context,2000));sections.push("","Outcome:",contractText(i.outcome),"","Scope:",contractText(i.scope),"","Preserved behavior:",contractText(i.preserved_behavior),"","Verification:",contractText(i.verification),"","Prohibitions:",contractText(i.prohibitions),`Do not commit, push, create pull requests, merge, or mutate GitHub. ${deployRule} Do not access secrets, invoke nested or other model workers, or touch unrelated files.`,"","Return compact evidence for the parent to inspect. Keep all work within the stated scope.");return `${sections.join("\n").slice(0,MAX_OUTPUT)}\n`;}
export function buildRunnerArgv(i:DelegateInput):string[]{const {mode,phase}=validateInput(i);const cwd=resolve(process.cwd(),i.cwd??process.cwd()),label=safeDelegateLabel(i.label);const a=["run","--mode",mode];if(i.route)a.push("--route",i.route);else if(i.orchestrator!=="eco")a.push("--routing-policy","runner-routing-v4");a.push("--phase",phase);if(phase==="deploy")a.push("--deploy-authorized","true");a.push("--task",taskContract(i),"--cwd",cwd,"--label",label);if(!i.route&&mode==="implement"&&i.workload_class)a.push("--workload-class",i.workload_class);if(i.task_class?.trim())a.push("--task-class",i.task_class.trim());if(i.route_rationale?.trim())a.push("--route-rationale",i.route_rationale.trim());if(i.task_slug)a.push("--task-slug",i.task_slug);return a;}
async function executable(p:string){try{const s=await stat(p);return s.isFile()&&(s.mode&0o111)?p:undefined;}catch{return undefined;}}
export async function discoverRunner(env=process.env,appCwd=process.cwd()){const configured=env.ARC_ORCHESTRATOR_BIN;if(configured){const x=await executable(resolve(appCwd,configured));if(!x)throw Error("ARC_ORCHESTRATOR_BIN is not executable");return x;}const self=process.argv[1]?resolve(process.argv[1]):"";for(const d of (env.PATH??"").split(delimiter).filter(Boolean))for(const n of ["arc-orchestrator","arc-orchestrator-runner","arc-runner"]){const p=resolve(d,n);if(p!==self){const x=await executable(p);if(x)return x;}}
 const moduleRoot=resolve(dirname(fileURLToPath(import.meta.url)),"../.."); const roots=[resolve(appCwd),moduleRoot]; const suffixes=["../arc-orchestrator/plugins/arc-orchestrator/bin/arc-orchestrator","../arc-orchestrator/plugins/pi-orchestrator/bin/arc-orchestrator","../arc-orchestrator/bin/arc-orchestrator","../arc-pi/bin/arc-orchestrator","vendor/arc-orchestrator/bin/arc-orchestrator","node_modules/@andysolomon/arc-orchestrator/bin/arc-orchestrator","node_modules/@andysolomon/arc-orchestrator/plugins/arc-orchestrator/bin/arc-orchestrator","node_modules/@andysolomon/arc-orchestrator/plugins/pi-orchestrator/bin/arc-orchestrator"];for(const root of roots)for(const suffix of suffixes){const x=await executable(resolve(root,suffix));if(x)return x;}throw Error("arc-orchestrator executable not found");}
const secret=/(?:token|secret|password|api[_-]?key|credential)\s*[:=]\s*[^\s,;]+/i;const secretGlobal=/(?:token|secret|password|api[_-]?key|credential)\s*[:=]\s*[^\s,;]+/gi;
const credentialLikeGlobal=/(?:-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----|-----END [A-Z0-9 ]*PRIVATE KEY-----|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{30,}|gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,}|glpat-[A-Za-z0-9_-]{20,}|npm_[A-Za-z0-9_-]{20,}|sk-[A-Za-z0-9_-]{10,}|xox[A-Za-z]-[A-Za-z0-9-]{10,}|eyJ[A-Za-z0-9_-]{2,}={0,2}\.[A-Za-z0-9_-]+={0,2}\.[A-Za-z0-9_-]+={0,2})/g;
const transcript=/(?:^|\n)\s*(?:user|assistant|system|tool)\s*:/i;const pathish=/(?:file:|[A-Za-z]:[\\/]|\\\\|(?<![\w])\/)[^\s,;)]*/g;
export function bounded(v:string,max=MAX_OUTPUT){const clean=v.replace(/[\u0000-\u001f\u007f]/g,"").replace(secretGlobal,"[redacted]").replace(credentialLikeGlobal,"[redacted]").replace(pathish,"[path]");return transcript.test(clean)?"[transcript redacted]":clean.slice(0,max);}
const arr=(v:string[],max:number)=>v.slice(0,20).map(x=>bounded(x,max));
/** Keep the end: ARC's final JSON is a line, and noisy diagnostics must not hide it. */
export function appendOutputTail(current:string,chunk:string,max=MAX_OUTPUT){const text=current+chunk;return text.length<=max?text:text.slice(-max);}
export function compactResult(stdout:string,processStatus="completed",meta:Record<string,unknown>={}){let p:any;for(const line of stdout.split(/\r?\n/).reverse()){try{const x=JSON.parse(line);if(x&&typeof x==="object"){p=x;break;}}catch{}}const valid=p&&!Array.isArray(p)&&["completed","blocked"].includes(p.status)&&typeof p.summary==="string"&&["changes","verification","risks","next_actions"].every(k=>Array.isArray(p[k])&&p[k].every((x:unknown)=>typeof x==="string"));const status=processStatus==="completed"&&valid?p.status:"blocked";return {...meta,status,summary:bounded(valid?p.summary:"runner did not produce a valid final result",2000),changes:valid?arr(p.changes,500):[],verification:valid?arr(p.verification,500):[],risks:valid?arr(p.risks,500):["runner execution was blocked or malformed"],next_actions:valid?arr(p.next_actions,500):[]};}
export async function hostCwd(value?:string){if(typeof value!=="string"||!value.trim()||value.includes("\0"))throw Error("invalid cwd");const p=isAbsolute(value)?value:resolve(process.cwd(),value);try{if(!(await stat(p)).isDirectory())throw 0;await access(p,constants.R_OK);return p;}catch{throw Error("cwd does not exist");}}
export type SessionRunStatus="running"|"completed"|"failed"|"timed_out"|"cancelled";
export interface ArcLivePhase { phase:string; status:string; model?:string }
export interface ArcLiveActivity { status:"waiting-provider"; tool?:string; count?:number }
export interface ArcLiveFile { file:string; status:string }
export interface ArcLiveSnapshot { v:1; eventsSeen:number; phase?:ArcLivePhase; phaseHistory:ArcLivePhase[]; activities:ArcLiveActivity[]; files?:{count:number;files:ArcLiveFile[]}; diffs:[] }
export type RegistryRecord={schemaVersion:1;sessionId:string;runId:string;label:string;mode:Mode;route:string;backend:string;model:string|null;cwd:string;status:SessionRunStatus;startedAt:string;heartbeatAt:string;staleAfterMs:number;phase?:Phase;workloadClass?:WorkloadClass;jobId?:string;liveActivity?:ArcLiveSnapshot;endedAt?:string;exitCode?:number|null;signal?:string|null;timedOut?:boolean};
const safeId=(x:string)=>typeof x==="string"&&/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(x)&&x!=="."&&x!=="..";const locks=new Map<string,Promise<void>>();
export async function writeRegistry(r:RegistryRecord,home=process.env.ARC_PI_HOME??(process.env.HOME?join(process.env.HOME,".arc-pi"):undefined)){if(!home||!safeId(r.runId)||!safeId(r.sessionId))return false;const dir=join(home,"session-runs",r.sessionId),file=join(dir,`${r.runId}.json`),previous=locks.get(file)??Promise.resolve();let release!:()=>void;const gate=new Promise<void>(x=>release=x);const queued=previous.then(()=>gate);locks.set(file,queued);await previous;try{await mkdir(dir,{recursive:true});let old:any;try{old=JSON.parse(await readFile(file,"utf8"));}catch{}if(old&&old.status!=="running")return false;const merged={...(old??{}),...r,liveActivity:r.liveActivity?copyLiveSnapshot(r.liveActivity):(old?.liveActivity?copyLiveSnapshot(old.liveActivity):undefined)};const tmp=`${file}.${randomUUID()}.tmp`;await writeFile(tmp,JSON.stringify(merged),{mode:0o600});await rename(tmp,file);return true;}catch{return false;}finally{release();if(locks.get(file)===queued)locks.delete(file);}}
export const spawn=nodeSpawn;
const eventPhases=new Set(["explore","analyze","research","plan","implement","verify","deploy","review"]),phaseStatuses=new Set(["preparing","waiting-write-lock","running","validating","completed","blocked","error"]),fileStatuses=new Set(["added","modified","deleted","renamed","unknown"]);
const onlyKeys=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&Object.keys(v).every(k=>keys.includes(k));
const safeInteger=(v:unknown,min:number):v is number=>Number.isSafeInteger(v)&&Number(v)>=min;
const liveSecret=/^(?:AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{30,}|gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,}|glpat-[A-Za-z0-9_-]{20,}|npm_[A-Za-z0-9_-]{20,}|sk-[A-Za-z0-9_-]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,})$/;
const safeLabel=(v:unknown,max:number)=>typeof v==="string"&&v.length>0&&v.length<=max&&/^[A-Za-z0-9][A-Za-z0-9._:/+@-]*$/.test(v)&&!secret.test(v)&&!liveSecret.test(v)&&!transcript.test(v);
const safeRepoPath=(v:unknown)=>{if(typeof v!=="string"||v.length===0||v.length>200||/^[\\/]|^[A-Za-z]:[\\/]|[\u0000-\u001f\u007f]/.test(v))return;const parts=v.replaceAll("\\","/").split("/");return parts.some(p=>!p||p==="."||p==="..")?undefined:parts.join("/");};
const sensitivePath=(p:string)=>p.toLowerCase().split("/").some(x=>x===".env"||x.startsWith(".env.")||[".npmrc",".pypirc",".netrc","credentials","credentials.json","id_rsa","id_ed25519",".aws",".ssh",".gnupg",".claude",".codex"].includes(x)||/\.(?:key|pem|p12|pfx|log)$/.test(x)||/(^|[._-])(prompt|transcript|conversation)([._-]|$)/.test(x)||/(^|[._-])(credentials?|secrets?|passwords?|tokens?|api[-_]?keys?|access[-_]?keys?|private[-_]?keys?)([._-]|$)/.test(x));
export function parseEvent(line:string){const prefix="arc-orchestrator: event: ";if(!line.startsWith(prefix))return;try{const e=JSON.parse(line.slice(prefix.length));if(!e||typeof e!=="object"||Array.isArray(e)||!onlyKeys(e,["v","kind","seq","at","data"])||e.v!==1||!safeInteger(e.seq,1)||!safeInteger(e.at,0)||!e.data||typeof e.data!=="object"||Array.isArray(e.data))return;const d=e.data as Record<string,unknown>;
 if(e.kind==="phase"){if(!["phase","status"].every(k=>k in d)||Object.keys(d).some(k=>!["phase","status","model"].includes(k))||typeof d.phase!=="string"||!eventPhases.has(d.phase)||typeof d.status!=="string"||!phaseStatuses.has(d.status)||(d.model!==undefined&&!safeLabel(d.model,80)))return;return {v:1,kind:"phase",seq:e.seq,at:e.at,data:{phase:d.phase,status:d.status,...(d.model!==undefined?{model:d.model}:{})}};}
 if(e.kind==="activity"){if(!("status" in d)||Object.keys(d).some(k=>!["status","tool","count"].includes(k))||d.status!=="waiting-provider"||(d.tool!==undefined&&!safeLabel(d.tool,40))||(d.count!==undefined&&!safeInteger(d.count,0)))return;return {v:1,kind:"activity",seq:e.seq,at:e.at,data:{status:"waiting-provider",...(d.tool!==undefined?{tool:d.tool}:{}),...(d.count!==undefined?{count:d.count}:{})}};}
 if(e.kind==="files"){if(!onlyKeys(d,["count","files"])||!safeInteger(d.count,0)||!Array.isArray(d.files)||d.files.length>20)return;const files:{file:string;status:string}[]=[];for(const x of d.files){if(!x||typeof x!=="object"||Array.isArray(x)||!onlyKeys(x as Record<string,unknown>,["file","status"]))return;const file=safeRepoPath((x as any).file),status=(x as any).status;if(!file||typeof status!=="string"||!fileStatuses.has(status))return;if(!sensitivePath(file))files.push({file,status});}if(d.count<files.length)return;return {v:1,kind:"files",seq:e.seq,at:e.at,data:{count:d.count,files}};}
 return;
 }catch{return;}}

const MAX_LIVE_EVENTS=200;
export function copyLiveSnapshot(s:ArcLiveSnapshot):ArcLiveSnapshot{return {v:1,eventsSeen:s.eventsSeen, ...(s.phase?{phase:{...s.phase}}:{}),phaseHistory:s.phaseHistory.slice(-6).map(x=>({...x})),activities:s.activities.slice(-5).map(x=>({...x})),...(s.files?{files:{count:s.files.count,files:s.files.files.slice(-20).map(x=>({...x}))}}:{}),diffs:[]};}
/** Map only already-validated ARC Pi v1 events; v2 diffs are intentionally not admitted yet. */
export function applyLiveEvent(snapshot:ArcLiveSnapshot,event:any):ArcLiveSnapshot{if(!event||snapshot.eventsSeen>=MAX_LIVE_EVENTS)return snapshot;const next=copyLiveSnapshot(snapshot);next.eventsSeen++;if(event.kind==="phase"){next.phase={...event.data};const p=next.phaseHistory.at(-1);if(!p||p.phase!==event.data.phase||p.status!==event.data.status||p.model!==event.data.model)next.phaseHistory=[...next.phaseHistory,{...event.data}].slice(-6);}else if(event.kind==="activity"){next.activities=[...next.activities,{...event.data}].slice(-5);}else if(event.kind==="files"){next.files={count:event.data.count,files:event.data.files.slice(0,20).map((x:any)=>({...x}))};}else return snapshot;return next;}
export function emptyLiveSnapshot():ArcLiveSnapshot{return {v:1,eventsSeen:0,phaseHistory:[],activities:[],diffs:[]};}
