import { defineTool } from "eve/tools";
import { always } from "eve/tools/approval";
import { z } from "zod";
import { buildRunnerArgv, compactResult, discoverRunner, hostCwd, spawn, writeRegistry, bounded, appendOutputTail, validateInput, taskContract, parseEvent, emptyLiveSnapshot, applyLiveEvent, copyLiveSnapshot, type DelegateInput, type RegistryRecord, type ArcLiveSnapshot } from "../lib/arc-runtime.js";
const workloads=["hard-heavy","hard-medium","hard-light","medium-heavy","medium-medium","medium-light","easy-heavy","easy-medium","easy-light"] as const;
const inputSchema=z.object({outcome:z.string().min(1),scope:z.string().min(1),verification:z.string().min(1),preserved_behavior:z.string().min(1),prohibitions:z.string().min(1),label:z.string().min(1).max(200),mode:z.enum(["analyze","implement","review"]).optional(),phase:z.enum(["explore","research","plan","implement","verify","deploy"]).optional(),route:z.string().optional(),context:z.string().optional(),cwd:z.string().optional(),task_class:z.string().optional(),route_rationale:z.string().optional(),workload_class:z.enum(workloads).optional(),orchestrator:z.literal("eco").optional(),implement_authorized:z.boolean().optional(),deploy_authorized:z.boolean().optional(),decision_refs:z.array(z.string()).optional(),assumption_refs:z.array(z.string()).optional(),readiness_acknowledged:z.boolean().optional(),task_slug:z.string().regex(/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/).optional(),background:z.boolean().optional()});
export const delegateTaskContract=(input:DelegateInput)=>taskContract(input);
function runnerArgv(input:DelegateInput,cwd:string){return buildRunnerArgv({...input,cwd});}
export function validateDelegateInput(input:DelegateInput){const result=validateInput(input);if(result.phase==="implement"&&!input.route&&!workloads.includes(input.workload_class as typeof workloads[number]))throw Error("automatic Implement requires one canonical workload_class");if(result.phase==="deploy"&&input.background===true)throw Error("Deploy must be synchronous");return result;}
export default defineTool({description:"ARC Delegate: exact bounded ARC contract requires outcome, scope, verification, preserved_behavior, prohibitions, and label, with optional context and refs. Explore, Research, Plan, Implement, Verify, and Deploy are always human-gated; Implement requires one canonical workload class and implement_authorized=true, while Deploy separately requires deploy_authorized=true and is synchronous-only. Metadata never replaces Eve approval.",inputSchema,approval:always(),async execute(raw,ctx){
 const input=raw as DelegateInput;let phase,mode,cwd,runner;
 try{({phase,mode}=validateDelegateInput(input));if(ctx.abortSignal?.aborted)return failure("request cancelled before runner spawn");cwd=await hostCwd(input.cwd);runner=await discoverRunner();if(ctx.abortSignal?.aborted)return failure("request cancelled before runner spawn");}catch(e){return failure(String(e));}
 const sessionId=(ctx as any).session?.id;const runId=`run-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;const started=new Date().toISOString();
 const record:RegistryRecord={schemaVersion:1,sessionId:typeof sessionId==="string"?sessionId:"",runId,label:bounded(input.label,200),mode,route:input.route??"",backend:"arc-orchestrator",model:null,cwd,status:"running",startedAt:started,heartbeatAt:started,staleAfterMs:30000,phase,workloadClass:input.workload_class,liveActivity:emptyLiveSnapshot()};
 const registry=await writeRegistry(record);
 const child=spawn(runner,runnerArgv(input,cwd),{cwd,shell:false,stdio:["ignore","pipe","pipe"],env:{...process.env,...(input.orchestrator?{ARC_ORCHESTRATOR_ORCHESTRATOR:input.orchestrator}:{})}});
 let timedOut=false,cancelled=false;const controller=new AbortController();const timeoutMs=Math.min(600000,Math.max(1000,Number(process.env.ARC_PI_DELEGATE_TIMEOUT_MS)||300000));const timer=setTimeout(()=>{timedOut=true;controller.abort();},timeoutMs);
 const abort=()=>{cancelled=true;controller.abort();};if((ctx as any).abortSignal?.aborted)abort();else (ctx as any).abortSignal?.addEventListener("abort",abort,{once:true});
 let stdout="", eventBuffer="", liveActivity:ArcLiveSnapshot=emptyLiveSnapshot(),terminalRecordStarted=false;let heartbeatWrites:Promise<unknown>=Promise.resolve();
 const processEventLine=(rawLine:string)=>{const line=rawLine.endsWith("\r")?rawLine.slice(0,-1):rawLine;if(!line.startsWith("arc-orchestrator: event: "))return;const e=parseEvent(line);if(!e)return;liveActivity=applyLiveEvent(liveActivity,e);const heartbeatAt=new Date().toISOString(),snapshot=copyLiveSnapshot(liveActivity);heartbeatWrites=heartbeatWrites.then(()=>terminalRecordStarted?false:writeRegistry({...record,heartbeatAt,liveActivity:snapshot}));};
 const consumeEventBuffer=(final=false)=>{const lines=eventBuffer.split(/\r?\n/);if(final)eventBuffer="";else eventBuffer=lines.pop()??"";for(const line of lines)processEventLine(line);};
 child.stdout?.on("data",(b:Buffer)=>{stdout=appendOutputTail(stdout,b.toString());});child.stderr?.on("data",(b:Buffer)=>{if(terminalRecordStarted)return;eventBuffer=appendOutputTail(eventBuffer,b.toString());consumeEventBuffer();});
 const result=await new Promise<{code:number|null}>(resolve=>{child.once("close",code=>resolve({code}));child.once("error",()=>{});controller.signal.addEventListener("abort",()=>{child.kill("SIGTERM");setTimeout(()=>child.kill("SIGKILL"),1000).unref();},{once:true});});clearTimeout(timer);
 consumeEventBuffer(true);await heartbeatWrites;terminalRecordStarted=true;const status=timedOut?"timed_out":cancelled?"cancelled":result.code===0?"completed":"failed";await writeRegistry({...record,status,heartbeatAt:new Date().toISOString(),endedAt:new Date().toISOString(),exitCode:result.code, timedOut,liveActivity:copyLiveSnapshot(liveActivity)});const out=compactResult(stdout,status==="completed"?"completed":"failed",{run_id:runId});if(!registry)out.risks.push("session registry unavailable");if(status!=="completed")out.risks.push(status);return out;
}});
function failure(summary:string){return{status:"blocked",summary:bounded(summary,500),changes:[],verification:[],risks:["runner was not started"],next_actions:[]};}
